INSERT INTO REGIONS (REGION_ID, REGION_NAME)
VALUES (2, 'Americas');

INSERT INTO COUNTRIES (COUNTRY_ID, COUNTRY_NAME, REGION_ID)
VALUES ('US', 'United States of America', 2);

INSERT INTO LOCATIONS (LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID)
VALUES (1400, '2014 Jabberwocky Rd', '26192', 'Southlake', 'Texas', 'US');

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID)
VALUES (60, 'IT', null, 1400);

INSERT INTO JOBS (JOB_ID, JOB_TITLE, MIN_SALARY, MAX_SALARY)
VALUES ('IT_PROG', 'Programmer', 4000, 10000);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY,
                       COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES (209, 'Peter', 'Griffin', 'PGRIFFIN', '590.424.4565', TO_DATE('09-09-2022', 'dd-MM-yyyy'), 'IT_PROG', 5500, null,
        null, 60);

INSERT INTO JOB_HISTORY (EMPLOYEE_ID, START_DATE, END_DATE, JOB_ID, DEPARTMENT_ID)
VALUES (209, TO_DATE('09-09-2022', 'dd-MM-yyyy'), TO_DATE('15-12-2022', 'dd-MM-yyyy') + 1, 'IT_PROG', 60);